apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 8080 //internal port
    targetPort: 80
    protocol: TCP
    name: http
    nodePort:  //The port to axpose to outer world. Starts from 30000
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: nginx
